---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Edit network information
- type: directory
  path: src/_data
  label: Network Information
  create: all
  match: "*.json"
  exclude: navigation.json
  new_doc_ext: json
- type: directory
  path: src/content/homepage
  label: Homepage
  create: documents
  match: "**/*"
- type: heading
  label: Website structure
- type: document
  path: src/_data/navigation.json
  label: Navigation Bar
- type: heading
  label: Edit Resources, Blog, Events, News
upload_dir: src/assets/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
