backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
site_url: "https://sdsn-rn-network.netlify.app"
media_folder: "src/assets/images"
public_folder: "images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        delete: false
        file: "src/index.md"
        slug: "{{slug}}"
        create: false
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/homepage.njk"}
          - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "News"
    label: "News"
    folder: "src/content/news"
    create: true
    slug: "{{slug}}"
    preview_path: "/{{slug}}" 
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/news-page.njk"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Resources"
    label: "News"
    folder: "src/content/news"
    create: true
    slug: "{{slug}}"
    preview_path: "/{{slug}}" 
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/resource-page.njk"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Events"
    label: "Events"
    folder: "src/content/events"
    create: true
    slug: "{{slug}}"
    preview_path: "/{{slug}}" 
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/events-page.njk"}
      - {label: "Body", name: "body", widget: "markdown"}
